/**
 * legal.ts — Server-only loader for the canonical MDX legal documents.
 *
 * The single source of truth lives at <repoRoot>/legal-content/<slug>.mdx and
 * is consumed by both the public website (this loader) and the React Native
 * app (via the /assets/legal copy generated by scripts/sync-legal-to-mobile.ts).
 */
import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import matter from "gray-matter";

export type LegalCategory = "core" | "disclosure" | "framework";

export interface LegalDocumentMeta {
  slug: string;
  title: string;
  category: LegalCategory;
  version: string;
  effectiveDate: string;
  lastUpdated: string;
  requiredAtSignup: boolean;
  requiresReacceptOnUpdate: boolean;
  isMaterialChange?: boolean;
  parentEntity: string;
  governingLaw: string;
  visibility?: "public" | "internal";
}

export interface LegalDocument {
  meta: LegalDocumentMeta;
  body: string;
  contentSha256: string;
}

const LEGAL_CONTENT_DIR = path.resolve(process.cwd(), "..", "legal-content");

/** All slugs that should appear in the public footer "Legal" section. */
export const PUBLIC_FOOTER_SLUGS: readonly string[] = [
  "terms",
  "privacy",
  "fees",
  "non-custodial",
  "payment-processor",
  "api-data",
  "identity-verification",
  "compliance-audit",
] as const;

/** Display label rendered in the footer (decoupled from frontmatter title for brevity). */
export const FOOTER_LABELS: Record<string, string> = {
  "terms": "Terms of Service",
  "privacy": "Privacy Policy",
  "fees": "Fee Disclosure Policy",
  "non-custodial": "Non-Custodial Disclosure",
  "payment-processor": "Third-Party Processor Disclosure",
  "api-data": "API & Data Usage Disclosure",
  "identity-verification": "Identity Verification Disclosure",
  "compliance-audit": "Compliance & Audit Logging Disclosure",
};

export function loadLegalDocument(slug: string): LegalDocument | null {
  const filePath = path.join(LEGAL_CONTENT_DIR, `${slug}.mdx`);
  if (!fs.existsSync(filePath)) return null;
  const raw = fs.readFileSync(filePath, "utf8");
  const parsed = matter(raw);
  const contentSha256 = crypto.createHash("sha256").update(raw, "utf8").digest("hex");
  return {
    meta: parsed.data as LegalDocumentMeta,
    body: parsed.content,
    contentSha256,
  };
}

export function loadAllLegalDocuments(): LegalDocument[] {
  return fs
    .readdirSync(LEGAL_CONTENT_DIR)
    .filter((f) => f.endsWith(".mdx"))
    .map((f) => loadLegalDocument(f.replace(/\.mdx$/, "")))
    .filter((d): d is LegalDocument => d !== null)
    .filter((d) => d.meta.visibility !== "internal");
}
